
        <ul>
            <?php 
                foreach ($categories as $categoryName)
                { 
                ?>
            
            <li>
                <article>
                    <h2> <?= $categoryName->getName(); ?></h2>
                    <a href="">Voir la catégorie</a>
                </article>
            </li>
            <li>
                <article>
                    <h2>Nom de la catégorie</h2>
                    <a href="">Voir la catégorie</a>
                </article>
            </li>
            <li>
                <article>
                    <h2>Nom de la catégorie</h2>
                    <a href="">Voir la catégorie</a>
                </article>
            </li>
            <?php
            }
            ?>
        </ul>




