<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf8" />
    <title>Distorsion</title>
     <link rel="stylesheet" href="assets/style.css">
  </head>
  <body>
    <?php 
      //charge le template que notre Controller a préparé 
       require $template;//ou require "templates/$template.phtml";
       
       
       
      // Inclusion des templates en fonction de la valeur de $route
			/*if (isset($route)) 
			{
				if ($route === 'connexion') 
				{
					require 'templates/login.phtml';
				} 
				else if ($route === 'space-perso')
				{
				    require 'templates/spacePerso.phtml';
				}
				else if ($route === 'notFound')
				{
					require 'templates/notFound.phtml';
				}
			}*/
    ?>
  <body>
</html>